["text", "category"]
["showRandomQuote", "random", "innerHTML"]
["Math.random"]
["createAddQuoteForm"]
["createElement", "appendChild"]
["newQuote", "document.getElementById", "addEventListener"]
["localStorage.setItem"]
["localStorage.getItem"]
"application/json", "JSON.stringify", "Blob"]
["FileReader", "onload", "JSON.parse", "readAsText"]
["populateCategories", "categoryFilter", "map"]
["option", "value", "textContent"]
["filterQuote", "quoteDisplay"]
["selectedCategory"]
["fetchQuotesFromServer", "function"]
["await", "async", "https://jsonplaceholder.typicode.com/posts", ".json"]
["method", "POST", "headers", "Content-Type"]
["syncQuotes"]
["setInterval"]
