["text", "category"]
["showRandomQuote", "random", "innerHTML"]
["Math.random"]
["createAddQuoteForm"]
["createElement", "appendChild"]
["newQuote", "document.getElementById", "addEventListener"]
["localStorage.setItem"]
["localStorage.getItem"]
